language: node_js
node_js: stable
before_script:
- bower install --silent
addons:
  sauce_connect: true
script:
- npm run lint
- polymer test --plugin sauce --job-name "chrome-xhr-request:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER}
cache:
  directories:
  - node_modules
branches:
  only:
  - stage
  - develop
after_success:
- node tasks/ci.js
env:
  global:
  - secure: VuHOEd0u5kKatPQ/RmzrRiFUXpA1mCIhrhNwpFK6Rk8HA4pgdkAV2BPXmL3oBpVvK3xMcAY1dOgavv2F2EEuq+VXm73UB0QTj5UYnW6iCtgDWH4ZOTTzbNJ9R6FyZTqN+TwpDpEIUpHGX4WUQvBvQ+xscsC+NJsyl50NkhREIcnOvmPED/VfNSZPNQZp3AvcyX1ZXUWDTnx57KcZ3mG1a146woOmCfbdYZrh4G85lDkN1LjjVwPUcnto7RMBwoCXe2pKz7nNDNylgoRmh/iIRyXBCZbib0HaiSbE7u1IkCckKakDhC9wPPuMDxjCUxqiJ/2ieFSP1EVvfQ6+xISQ41bLULJW5r+7H/nufdUMzTfe2vtGnyeXh0M2pRKB4M7p3vmsdC3l4uz9qc1HF4dslTIoG3wn5X2wXHOayIzNzt7rl6dYNjx5/GtD+i4Lq2260911z/t7ELhxh04pATtOb4rhg9Q8Q6KLNtlTB8HeASft02VMvZ2l4nzYxAaptRGm2S8ON5YU7KUgB0K1ePd+Bq7l6UewOX6Dco7CAGTuoSCc2BjTgymrf13F1sybzDbCr9QWY8XPhGtLoEE/ikDVWlk+g/AqV7OygWZFxw7xwuI9uBtQdQEpTVZB60XPTP2gNw28SMGmYGqAdN74qkpJWwkwQ8I5F0TOORGvB6vyKt4=
  - secure: POQU5VCjKWH7xk2nKeH5g2WZi5GCyDMPbO73FQCZw+mScVULrlBW15ACVwe1nAfmEDIpKfyFfBYDX3LfTThCdnB3DsPhZUGR4Gs2ATs9L7Kmm8MhbnJiORI1k2utO+flKyEKgR2TkBQqcs/rlLNdLiKL0WoVLlGNJ2+t1M8V5/SfMbgztYEOZ+Rv9IApb7p6mejCQISXQz/6NXq1lvZaAl6ZZXPTh9p0UOeKfzzksRX3iMaK91UmnT60pgjPf/IbFxM5bzIUpeS4PT+7UM1ifiG3jEXmFtuSUu7jnHjrvqg8VjUWkiGZsoBaHiXzLQgUcGqdeg8vGsBPhnlzolatGFClfwrKL0SMfEDt3Pf0lQXuuVLWRoFLbMn5Ic8pq8cRU2eI6x/IsFI9gSb/YqrB0hOWr5NBHf+tdWONLvyVmbmO1XmHuYqA1doZfbLFdE+NNeVFnrk9mSZt8DlKVAEOTIxz4FNceWe5CfiXGv36IS+4D6+jNUhq0Zu0m0CTCci+7II1d0E5c+1iLHhOhKMozLgMtgYQquH8rX1szq0cysorAKlwAZ/2Th4ErlzIOv7iE3annPZYDJoopYuZXqba1EcRTRNnEvQE38JeGb6WiAABlg/c6jEwOyPIk5OvEFmem8nXGBxjts9hsvKyjLnwsEdCWw8WFRTHeXk17YW1YZE=
